Updated workflows
stemcellcommons/scc-galaxy-tools pull request #1
Opened 2017-10-05 20:33 UTC by scottx611x

Includes our updated Workflows from Release 1.6.0

- [x] Add Updated WF names
- [x]  Update `repository_dependencies.xml`
- [ ] Add updated WF descriptions
- [ ] Add updated input file names/descriptions

2017-10-06 14:55 UTC, hackdna requested changes

2017-10-06 14:55 UTC, hackdna commented on chipseq_workflows/repository_dependencies.xml
> +  <repository toolshed="testtoolshed.g2.bx.psu.edu" name="split_paired_collection" owner="scottx611x" changeset_revision="429cae20b148" />
This tool should be published in https://toolshed.g2.bx.psu.edu/view/refinery-platform and the source code should be in https://github.com/refinery-platform/galaxy-tools.

2017-10-06 14:55 UTC, hackdna commented on rnaseq_workflows/repository_dependencies.xml
> +  <repository toolshed="testtoolshed.g2.bx.psu.edu" name="split_paired_collection" owner="scottx611x" changeset_revision="429cae20b148" />
This tool should be published in https://toolshed.g2.bx.psu.edu/view/refinery-platform and the source code should be in https://github.com/refinery-platform/galaxy-tools.

2017-10-06 19:39 UTC, scottx611x commented
@hackdna Yeah thanks, this isn't ready yet though. I'll request a review from you when it is.

2017-10-06 19:52 UTC, hackdna commented
OK. I replied because I've received a notice asking for a review of this PR.

2017-10-11 20:52 UTC, scottx611x commented
@hackdna This is ok to review now

2017-10-12 18:12 UTC, hackdna requested changes

2017-10-12 18:12 UTC, hackdna commented on chipseq_workflows/repository_dependencies.xml
> +  <repository toolshed="toolshed.g2.bx.psu.edu" name="split_paired_collection" owner="scottx611x" changeset_revision="7432970f4f80" />
As I mentioned earlier, this tool should be published in https://toolshed.g2.bx.psu.edu/view/refinery-platform

2017-10-16 13:59 UTC, scottx611x commented on chipseq_workflows/repository_dependencies.xml
> +  <repository toolshed="toolshed.g2.bx.psu.edu" name="split_paired_collection" owner="scottx611x" changeset_revision="7432970f4f80" />
I've granted the `refinery-platform` user write access to that repository. I don't have the ability to publish tools as `refinery-platform`

2017-10-16 18:41 UTC, hackdna commented on chipseq_workflows/repository_dependencies.xml
> +  <repository toolshed="toolshed.g2.bx.psu.edu" name="split_paired_collection" owner="scottx611x" changeset_revision="7432970f4f80" />
I've provided you with access info.

2017-10-17 13:38 UTC, scottx611x commented on chipseq_workflows/repository_dependencies.xml
> +  <repository toolshed="toolshed.g2.bx.psu.edu" name="split_paired_collection" owner="scottx611x" changeset_revision="7432970f4f80" />
@hackdna Okay so if the `refinery-platform` user is to be the primary owner of the `split-paired-collection` tool I would need to deprecate the current tool, and upload that same code under a different name than `split-paired-collection`. I think Galaxy prefers what I've already done (making the `refinery-platform` user an admin of the repo) from what I read here: https://galaxyproject.org/toolshed/repository/#manage-repository-administrators

2017-10-17 15:05 UTC, hackdna commented on chipseq_workflows/repository_dependencies.xml
> +  <repository toolshed="toolshed.g2.bx.psu.edu" name="split_paired_collection" owner="scottx611x" changeset_revision="7432970f4f80" />
Right, all Refinery-related tools should be in https://toolshed.g2.bx.psu.edu/view/refinery-platform then all individual accounts should be provided access to those repos as necessary.

2017-10-17 21:26 UTC, scottx611x commented
@hackdna This is ok to review again

2017-10-19 19:59 UTC, merged